#!/usr/bin/env bash

BRANCH=$(git rev-parse --abbrev-ref HEAD)
REGEX="^(main|develop|((feature|release|hotfix)\/[A-z0-9].+))$"

if ! [[ $BRANCH =~ $REGEX ]]; then
  echo ""
  echo "Your commit was rejected due to branching name"
  echo "Please rename your branch with $REGEX syntax"
  echo ""
  exit 1
fi